import test from 'node:test';
import assert from 'node:assert/strict';
import { superstars } from '../js/data/superstars.js?v=1.1.23';
import { decks } from '../js/data/decks.js?v=1.1.23';
import { allGameplayCards } from '../js/data/content.js?v=1.1.23';
import { MatchEngine } from '../js/engine/MatchEngine.js?v=1.1.23';
import { cpuDecision } from '../js/ai/WrestlingAI.js?v=1.1.23';
const card=id=>allGameplayCards.find(c=>c.id===id); const star=id=>Object.values(superstars).find(s=>s.id===id); const rng=()=>.99;
function ready(cpu='bayley',opp='cm-punk'){const g=new MatchEngine({p1:star(opp),p2:star(cpu),decks,rng});const s=g.state(),p=s.players.p2;s.phase='ACTION';s.playerInControl='p2';s.proposedMove=null;s.postMove=null;p.turn={momentumPlayed:0,momentumPlayLimit:1,actionPlayed:0,supportPlayed:0,specialPlayed:0};p.momentum={strength:4,strike:4,technical:4,agility:4,attitude:5};p.adrenaline=5;return{g,s,p};}
test('v0.13.17 CPU uses a signature tutor Action when it creates a live follow-up',()=>{const{g,p}=ready('bayley');p.hand=[card('bayley-ding-dong-hello'),card('punch')];p.deck=[card('bayley-to-belly'),card('dropkick')];const d=cpuDecision(g,'p2');assert.equal(d?.type,'action');assert.equal(d?.card?.id,'bayley-ding-dong-hello');});
test('v0.13.17 CPU installs a legal Manager before spending the Control sequence',()=>{const{g,p}=ready('brock-lesnar');p.hand=[card('manager-paul-heyman'),card('punch')];p.deck=[card('brock-lesnar-brocks-german'),card('dropkick')];const d=cpuDecision(g,'p2');assert.equal(d?.type,'manager');assert.equal(d?.card?.id,'manager-paul-heyman');});
test('v0.13.17 CPU saves Once Too Often for dangerous repeats instead of burning it on trivial repeats',()=>{const{g,s,p}=ready('cm-punk','seth-rollins');const once=card('once-too-often'),punch=card('punch'),curb=card('seth-rollins-curb-stomp');p.hand=[once];s.phase='COUNTER';s.proposedMove={attackerId:'p1',defenderId:'p2',card:punch};s.players.p1.events.connectedCardIdsMatch[punch.id]=1;assert.equal(cpuDecision(g,'p2')?.type,'passCounter');s.proposedMove={attackerId:'p1',defenderId:'p2',card:curb};s.players.p1.events.connectedCardIdsMatch[curb.id]=1;const d=cpuDecision(g,'p2');assert.equal(d?.type,'counter');assert.equal(d?.card?.id,'once-too-often');});
test('v0.13.17 CPU avoids zero-net hand-filter Actions that would only consume the Action window',()=>{const{g,p}=ready('brock-lesnar');p.events.connectedCardNamesThisControl['Brock’s German']=true;p.hand=[card('brock-lesnar-eat-sleep-conquer-repeat'),card('punch')];const d=cpuDecision(g,'p2');assert.notEqual(d?.card?.id,'brock-lesnar-eat-sleep-conquer-repeat');});
